### ISSUE TITLE
Drupal presence in pattern lab (in project scaffolding + in js/twig)

### ISSUE THREAD

**Issue by jesconstantine** [massgov/mayflower-patternlab#1]
Hoping to start a conversation about decoupling drupal from the pattern lab style guide.  I see two opportunities here:
1. project scaffolding: this current scaffolding seems to imply that our style guide will ship along with / inside of a drupal theme, which is not something that we want (as our goal is to use the style guide twig/css/js assets across the enterprise in other applications, also, perhaps pattern lab will outlive drupal)
2. pattern lab edition choice: I believe on our phone call last Thursday (with Velir-Palantir-MassIT) I heard that the drupal standard edition of pattern lab was going to be used.  I wanted to suggest that we instead use the twig standard edition.  This will ensure that pattern lab knows nothing about drupal (either in its js or twig filters/components).  We don't want pattern lab to be making any environment assumptions.

I think the coupling will come in on the drupal theme's end, using its twig templates as a Presenter (as in [MVP architecture](https://micah.codes/a-new-design-system-architecture/)) routing the drupal data model through to the pattern lab view twig template via embeds/includes/etc.

What do people think?

Also - FYI - here are some initiatives that we've been following in the drupal / components community:
- Wim’s patch: [register components with Drupal](https://www.drupal.org/node/2702061)
- John Albin’s Component Libraries modules: [register namespaces](https://www.drupal.org/project/components)
- D8 version of [Zen](https://www.drupal.org/node/2614448)
- Micah Godbolt's [Pattern Builder module](https://www.drupal.org/project/patternbuilder)
- [Drupal Twig Slack](https://drupaltwig-slack.herokuapp.com/): A great place to learn from the above folks in the community - they have weekly wednesday meetings!

**Comment by jasonstanbery** [comment]
@jesconstantine Jonathan is getting back from vacation today. So we're going to chat, but there is a dev branch that is just the twig standard edition that is likely what we're going to use going forward. I just didn't want to delete the other branch until Jonathan and I had a chance to discuss.

But it sounds as if you & I are on the same page.
