### ISSUE TITLE
I need consistent 'ma__contact-group' divs and contact-group.twig needs to support a textarea for address.

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#185]
![screen shot 2016-11-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/231467/20153991/550b3a20-a693-11e6-9e15-3fb6e2320cf4.png)

Like this (in the aside.sidebar):
```
<div class="ma__contact-group">.....</div>
<div class="ma__contact-group">.....</div>
<div class="ma__contact-group ma__contact-us__extra js-accordion-content">.....</div>
<div class="ma__contact-group">.....</div>
<div class="ma__contact-group">.....</div>
```

-- and I need molecules/contact-group.twig to support a textarea address. In this instance we are using a simple textarea for the address.

```
251 Causeway Street
Suite 900
Boston, MA 02114-2104
```

**Comment by gender404** [comment]
Not sure what "supporting a text area" means.  You should be able to put all the text from a text area within a single contact-us__address div instead of stacking them.  I'm not sure how you plan on doing line breaks though.  That's why I built it as separate items.

As for the consistency, is the issue that some of the contact-us__group items are wrapped in the contact-us__extra div?

**Comment by nstriedinger** [comment]
In a system structure, we know we have another "row", if you will, with a icon, type, and (for address) `<textarea>....</textarea>` to pass into the template. This works correctly for Phone & Email, etc. That's why, contact-group.twig, need to hold an additional "textarea" for address (or a more generic term) at this moment. Another words, contact-group needs to cater to every "type" of content inside the "group".

We have a plan for line-breaks. 

Make sense? 

Yes, correct. We need consistency here.

**Comment by gender404** [comment]
I think I can add "address" as a type to the contact Group without any real issues.

Not sure how I would remove the wrapper around the hidden contact-groups though.  Accordions need a wrapping container to make them work properly.

**Comment by nstriedinger** [comment]
@legostud Would you like me to take care of this? @lukewertz

**Comment by nstriedinger** [comment]
@legostud Furthermore, we can eliminate superfluous logic because I can take care of "tel:+" & "mailto:" on the backend...

```
<div class="ma__contact-group">
  <h6 class="ma__contact-group__name">
    {% include contactGroup.icon %}
    <span>{{contactGroup.name}}</span>
  </h6>
  {% for item in contactGroup.items %}
    <div>
      {% if item.label %}
        <span class="ma__contact-group__label">{{item.label}}:</span>
      {% endif %}
      {% if item.type == "phone" %}
        <a href="tel:+{{item.link}}" class="ma__contact-group__value ma__contact-group__value--phone">{{item.value}}</a>
      {% elseif item.type == "email" %}
        <a href="mailto:{{item.link}}" class="ma__contact-group__value ma__contact-group__value--email">{{item.value}}</a>
      {% else %}
        <a href="{{item.link}}" class="ma__contact-group__value">{{item.value}}</a>
      {% endif %}
    </div>
    {% if item.details %}
      <p class="ma__contact-group__details">{{item.details}}</p>
    {% endif %}
  {% endfor %}
</div>
```

**Comment by lukewertz** [comment]
@nstriedinger Just following up with you here for @legostud's benefit.

Yes, you have bandwidth and this is a relatively small job. Please put up a PR for @legostud to review that fixes this issue.

**Comment by gender404** [comment]
@lukewertz - thanks for offering to help, but this is not as small a job as you would think.  I am however working on making the modifications needed to get an address to display within a contact group.

These changes affect the JSON format so any component/page in Patternlab that uses the contact group module will need to be updated.

**Comment by gender404** [comment]
@nstriedinger - the logic around type is deeper than just adding tel:+ or mailto:.  Please note that the class name is also changing based on the type of link they are using.

**Comment by gender404** [comment]
```
<div class="ma__contact-group">
  <h6 class="ma__contact-group__name">
    {% include contactGroup.icon %}
    <span>{{contactGroup.name}}</span>
  </h6>
  {% for item in contactGroup.items %}
    <div>
      {% if item.label %}
        <span class="ma__contact-group__label">{{item.label}}:</span>
      {% endif %}
      {% if item.type == "phone" %}
        <a href="tel:+{{item.link}}" class="ma__content-link ma__content-link--phone">{{item.value}}</a>
      {% elseif item.type == "email" %}
        <a href="mailto:{{item.link}}" class="ma__content-link">{{item.value}}</a>
      {% elseif item.type == "address" %}
        <div class="ma__contact-group__address">
          {{item.value | raw}}
        </div>
        <a href="{{item.link}}" class="ma__content-link ma__content-link--chevron">directions</a>
      {% else %}
        <a href="{{item.link}}" class="ma__content-link">{{item.value}}</a>
      {% endif %}
    </div>
    {% if item.details %}
      <p class="ma__contact-group__details">{{item.details}}</p>
    {% endif %}
  {% endfor %}
</div>
```

**Comment by nstriedinger** [comment]
@lukewertz -- Are implementing a "directions" link? This is an addition.
`<a href="{{item.link}}" class="ma__content-link ma__content-link--chevron">directions</a>`

**Comment by gender404** [comment]
That might be a leftover from when I was trying to use the contact-us molecule in the action header.  I'll wrap it in a conditional so it can be optional.

**Comment by nstriedinger** [comment]
@legostud ahh, yeah, I see this now in contact-us.twig. Pardon.

**Comment by gender404** [comment]
I think this is all set now.
