### ISSUE TITLE
Remove hardcoded paths in Javascript.

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#197]
Please remove hardcoded paths. Add a JS global "directory" setting variable for paths. In this instance, use it for '/assets/'.

For example:
`richText.js -   fetch('/assets/images/svg-sprite/external-link.svg'`

`$.ajax({
         url : '/assets/js/templates/' + name + '.html',`

This should be in a separate file, maybe called 'settings.js' and not aggregated in.

Something like this
* create a new file called `env.js`
* add `var themePath = '/assets';`
* update code like so:` fetch(themePath + "/images/svg-sprite/external-link.svg"`
* include separately from` index-generated.js` and `vendor-generated.js`

**Comment by gender404** [comment]
Looks like you fixed this already.  Sorry I wasn't able to get to it before my long weekend.
