### ISSUE TITLE
Minor Button

### ISSUE THREAD

**Issue by lukewertz** [massgov/mayflower-patternlab#201]
The "Minor Button" atom doesn't follow either variable names or internal/external styling patterns used nearly everywhere else.

See: https://github.com/massgov/mayflower/blob/dev/styleguide/source/_patterns/01-atoms/01-buttons/button-link2-sm.twig

I'd ask that this atom be refactored to use the variables `type` (for internal/external), `href` (instead of link) and `text` should remain unchanged.

**Comment by gender404** [comment]
I can change the "link" to "href".  These buttons weren't designed to have the internal/external treatments.  Is there a reason why you would need to add those treatments?

**Comment by gender404** [comment]
This should be resolved in the latest Release 2.1.0

**Comment by lukewertz** [comment]
If this is resolved, we should close this issue.
