### ISSUE TITLE
UTILITY Drawers: These need to be generalized.

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#324]
This "body" field needs to account for:
* description text
* and any links added

* So if we have just a description, this is styled one way
* So if we have a description and a few links, this is styled the same but includes the links.

Also with links, currently under "log in to..." shouldn't this account for two links?

![screen shot 2017-02-02 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/231467/22565045/cabead02-e954-11e6-8c01-e7b938172158.png)

![screen shot 2017-02-03 at 10 28 15 am](https://cloud.githubusercontent.com/assets/231467/22596964/a54a781a-e9fb-11e6-927c-e1aa564b89d6.png)

**Comment by gender404** [comment]
yeah, that makes sense.  Originally all of these drawers were completely different, but with the latest updates I can see that they are more similar now.  Sorry about not noticing that earlier.

The simplest fix I can see to unblock you would be for me to rename the login-util version to utility-drawer (file names, class names, data utilityDrawer).  Fixing the styling could be done with a new Jira ticket next sprint.  Would that work for you?
