### ISSUE TITLE
Check for link on 'ma__image-promo__link'

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#378]
If we don't have a link, we still see an `js-clickable-link` arrow.

![screen shot 2017-03-27 at 11 28 08 am](https://cloud.githubusercontent.com/assets/231467/24364361/94d482f6-12e0-11e7-8358-b755a95c535d.png)

**Comment by gender404** [comment]
I don't see how this is possible.  That link already as a conditional wrapping it to check if it exists.  Is the below conditional not sufficient?

    {% if imagePromo.link %}
      <div class="ma__image-promo__link">
        {% set decorativeLink = imagePromo.link %}
        {% include "@atoms/decorative-link.twig" %}
      </div>
    {% endif %}

**Comment by gleroux02** [comment]
@nstriedinger looking at this again, are you using the action-activities molecule? Use the image-promo one instead. That is what action-activies is actually rendering with and will set and check the link properly.

**Comment by mrossi113** [comment]
@nstriedinger @gleroux02 is this issue being fixed? For we have bug ticket that was created for the same issue on Maintenance & Support. [DP-2161-Activities Paragraph shows link icon when there is no link](https://jira.state.ma.us/browse/DP-2161 )

**Comment by nstriedinger** [comment]
@gleroux02 @legostud imagePromo by itself does not support arrays, so in the context of a section on, say, a Location Page (with section titles & IDs), this does not work. Each Section expects --   
```
"title":"Activities",
      "intro": "",
      "id":"activities",
      "path": "molecules-action-activities",
      "data" [ imagePromo does not support arrays ]
```
so 'actionDetails' freaks out or I only display one Action Activity.

It's totally possible, that I'm not working with this as expected. Thoughts?

**Comment by gender404** [comment]
Interesting issue.  This does get resolved in Release 4 with a new Image Promos (plural) organism.
