### ISSUE TITLE
Under Hours we need to check for "label" and if so, remove border? - background-color: rgba(67,149,111,0.5); }

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#379]
We need to be able to fit multiple Hours/Time Frame under sections. Maybe this is ok looking?

![screen shot 2017-03-27 at 2 43 43 pm](https://cloud.githubusercontent.com/assets/231467/24372393/d6680628-12fb-11e7-86f1-13db6271759c.png)

![screen shot 2017-03-27 at 2 41 18 pm](https://cloud.githubusercontent.com/assets/231467/24372334/a3a5db16-12fb-11e7-96db-06f9441ed2e8.png)

**Comment by gender404** [comment]
We never built an Hours component.  It was just coded as part of Rich Text.

**Comment by gleroux02** [comment]
Closing this issue out. The issue can and should be resolved within drupal.
