### ISSUE TITLE
This looks odd without a sidebar?

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#390]
![screen shot 2017-04-05 at 9 59 30 am](https://cloud.githubusercontent.com/assets/231467/24709040/aada3fe8-19e6-11e7-8f29-9adc96b035b4.png)

**Comment by gender404** [comment]
That should be fixed in Release 4.0

**Comment by gleroux02** [comment]
@legostud since release 4.0 won't be available for a little while, can we cherry pick those changes for a 3.x release?

**Comment by gender404** [comment]
I pushed up a fix for it.
