### ISSUE TITLE
Javascript TypeErrors - Can you wrap generated code

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#398]
Sets the value of $ locally in the function scope, that way we use $

jQuery(function($) {
......
//# sourceMappingURL=index-generated.js.map
});

So we can get rid of TypeErrors and use your JS directly. There may be a better/different way to do this with your compression/aggregation tools. Please investigate and implement.

![screen shot 2017-04-12 at 11 34 23 am](https://cloud.githubusercontent.com/assets/231467/24966704/ba92473e-1f75-11e7-9903-081ee461ad6d.png)

**Comment by gender404** [comment]
I think this should fix it.  0a0ad063820aadda1364fc3621cb46831c882045

I switched $ to jQuery instead

**Comment by nstriedinger** [comment]
awesome! thx!
