### ISSUE TITLE
linkList Issue with href/url

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#448]
Working on a linkList and noticed no href/url rendering.
Thoughts?

![screen shot 2017-05-24 at 12 44 02 pm](https://cloud.githubusercontent.com/assets/231467/26415079/3d5073ce-407f-11e7-830d-a89f79327785.png)

**Comment by gender404** [comment]
yup that's a typo

do you want me to fix and create a pre-release tag for it?

**Comment by gender404** [comment]
would it be feasible to change the data object for linkList to use href instead of url.  That way each link object will match the decorative link object?

**Comment by gender404** [comment]
https://github.com/massgov/mayflower/pull/454

PR created.  we can put a tag on that branch if needed.
