### ISSUE TITLE
pressListing not working b/c of url/href issue...

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#491]
![screen shot 2017-06-27 at 4 01 32 pm](https://user-images.githubusercontent.com/231467/27607461-f679d2ea-5b51-11e7-8d00-6a2850f4833c.png)

**Comment by gender404** [comment]
@nstriedinger - does this Pull Request fix your issue?

https://github.com/massgov/mayflower/pull/492
