### ISSUE TITLE
view all pages not loading stylesheets properly

### ISSUE THREAD

**Issue by clairesunstudio** [massgov/mayflower-patternlab#508]
![screen shot 2017-07-12 at 9 44 07 am](https://user-images.githubusercontent.com/5789411/28122807-4a942726-66ed-11e7-81e7-0fa10dfc97bc.png)

http://mayflower.digital.mass.gov/?p=all
http://mayflower.digital.mass.gov/?p=viewall-organisms-all
http://mayflower.digital.mass.gov/?p=viewall-templates-all
... 
seems like a recent issue (I have only noticed it as of yesterday)

Jira ticket: https://jira.state.ma.us/browse/DP-4432

**Comment by jesconstantine** [comment]
This is something we'll want to keep our eyes out for, see if it becomes a pattern.  But it appears to be resolved for now.
