### ISSUE TITLE
Add |raw to ma__listing-table row so I can add linebreaks

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#516]
![screen shot 2017-07-21 at 4 24 15 pm](https://user-images.githubusercontent.com/231467/28481009-24587224-6e31-11e7-849c-5af8a0073a4f.png)

**Comment by gender404** [comment]
@nstriedinger - This should really be a Jira ticket so Joe G. can prioritize the work

**Comment by nstriedinger** [comment]
Pardon, you've already added this to 5.4.0. I was just behind a few versions.
