### ISSUE TITLE
Press Dateline needs to be re-worked to use something like this.

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#598]
We can't use paragraph attributes. Thoughts? Can we do something like this?

![screen shot 2017-09-18 at 9 48 24 am](https://user-images.githubusercontent.com/231467/30545134-bf391476-9c56-11e7-89ab-8f62cda839d1.png)

**Comment by gender404** [comment]
I had something like that originally, but I changed it because they wanted "Boston" to be a variable.  Wasn't sure how / if you could insert it into the first paragraph of a Rich Text editor.

**Comment by nstriedinger** [comment]
I can insert it ok, but I can't use paragraph attributes. Can you rework this with the markup sample I provided. Greg wants it to be a `<span>` inside the `<p>` tag.

**Comment by gleroux02** [comment]
@nstriedinger please do the mayflower work here. We should be doing the PRs needed and not creating issues.

**Comment by nstriedinger** [comment]
@gleroux02 @legostud Ok, I'll re-work it. Thanks

**Comment by jesconstantine** [comment]
Closing issue as work is done in #599
